# This playbook installs the epel tools onto the the specified centos boxes

- name: run tasks on all hosts
  hosts: centos
  tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: present
        update_cache: true
      become: true