- hosts: masternode0
  become: yes
  tasks:
  - name: get the kubeadm join command from master
    shell: kubeadm token create --print-join-command 2> /dev/null
    register: join_command_out

  - name: set join command
    set_fact:
      join_command: "{{ join_command_out.stdout_lines[0] }}"
  

- hosts: workers
  tasks:

  - name: join the worker nodes to the cluster
    become: true
    shell: "{{ hostvars['masternode0'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt